apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-mongodb-secrets
  namespace: mongodb
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-batch-secrets
  namespace: batch
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
