apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /metabase-data
              name: metabase-storage
          env:
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: metabase-storage
          persistentVolumeClaim:
            claimName: metabase-pvc
